name: CI Build And Test

on:
  push:
    branches: ["master", "feature/hexagonal"]
  pull_request:
    branches: ["master", "feature/hexagonal"]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (Maven, Java 11)
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Build (skip tests)
        shell: bash
        run: |
          if [ -f mvnw ]; then
            chmod +x mvnw
            ./mvnw -B -ntp -DskipTests clean package
          else
            mvn -B -ntp -DskipTests clean package
          fi

  test:
    name: Test (Maven, Java 17
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          cache: 'maven'

      - name: Run Tests
        shell: bash
        run: |
          if [ -f mvnw ]; then
            chmod +x mvnw
            ./mvnw -B -ntp verify
          else
            mvn -B -ntp verify
          fi